- bluepy/btle.py
Set of 5 patches, the first solves issue #27, the rest contains error suppressing, cleaning, renaming. The last commit adds displaying of characteristic properties, so it's easier to know what can be done (read/notify/write etc) with a characteristic.
Add option to use "random" address type.
Rename devaddr to devAddr  
Remove not used definitions of security level
Do not try to read characteristic if it doesn't suport reading
Add displaying characteristic properties
> Solve issue #27 + some other changes

- .gitignore
- bluepy/bluepy-helper.c
Some peripherals will issue ATT requests to the central when they want / need to use specific services.  With the current bluepy implementation, no response was sent for these requests, the specifications clearly state that if no response is received within 30 seconds, the request initiator should tear down the link (this is what was observed with FitBit devices).  So this change sends error responses to make sure the device will not disconnect.
This could also be seen as he starting point for the development of central based services (which I will probably do in a near future and will share).  The code is structured to quickly allow this extension
> Import GATT server basic support

- bluepy/btle.py
- bluepy/line_reader.py
When there are two lines available for reading from the subprocess,
Python readline() actually reads all data from the pipe. This makes
the subsequent select.poll() not triggered as expected.
LineReader buffers all available data after select.poll() returns.
Its readline() method only polls again when there is no available
data in the buffer.
> Buffer all the available data in LineReader

- bluepy/btle.py
binascii.a2b_hex() against str was causing errors on python 3.2.3.
> make it run on python3

- bluepy/bluepy-helper.c
Hello Ian,
With the update to bluez 5.29, the write without response support in bluepy-helper is broken, could you merge in this change?
I have just added another patch: when the python script was asserting , bluepy-helper process was not exiting.  This was preventing restarting a script.
Thanks
Louis
> Fix write without response and exit on python script exception/assertion

- bluepy/bluepy-helper.c
- bluepy/btle.py
This is the small fix associated with the issue i just opened.
The mgm functions registered to enable scanning leak responses across all helper processes which causes problems for peripherals that are connected.
With this fix I can run a single scanning thread side-by-side with multiple device threads, each with their own running bluepy-helper process. 
You cannot run multiple scanning helpers concurrently however.
> Add cmdline argument to bluepy-helper for scanning

- bluepy/__init__.py
The idea of this code is to expose the btle and tagsensor once you import ``bluepy``
```python
import bluepy
bluepy.btle # works with this trick
```
> Exposing btle and tagsensor to the top level module

- setup.py
My Docker didn't had all dependencies set up yet so I got the following error. Python 3 does not allow concatenating bytes and strings.
```
Traceback (most recent call last):
File "/tmp/pip-build-y7otqrxw/bluepy/setup.py", line 16, in pre_install
msgs = subprocess.check_output(shlex.split(cmd), stderr=subprocess.STDOUT)
File "/usr/local/lib/python3.4/subprocess.py", line 620, in check_output
raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['make', '-C', './bluepy']' returned non-zero exit status 2
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-y7otqrxw/bluepy/setup.py", line 70, in <module>
'blescan=bluepy.blescan:main', …
```
> Fix error reporting when compile fails.

- bluepy/btle.py
To have the same behavior as Peripheral.writeCharacteristic(...)
> Add a missing return in the Characteristic.write functio

- bluepy/btle.py
It was confusing to me using this library at first that the services field was empty and the getServices method had to be called first to cache them. I think it would be more convenient to hide the caching implementation from the users. The getServices method could be removed or deprecated.
There was also a discrepancy with `addr` vs `deviceAddr` to hold the MAC address.
> Use Peripheral.services as a property

- bluepy/btle.py
This isn't really ready to merge yet; I'd like to get feedback on how to handle descriptors first.
I've added the ability to retrieve descriptors by grabbing all of the handles in a service's or characteristic's range and filtering out the handles that correspond to things we don't usually think of as descriptors (like the descriptor for declaring a characteristic's properties or the descriptor for declaring a primary service).
With the new `Characteristic.getDescriptor()` method, setting up notifications now looks like:
```
char = peripheral.getCharacteristics(uuid=your_uuid_here)[0]
ccc_desc = char.getDescriptors(forUUID=0x2902)[0]
ccc_desc.write(b"\x01")
```
Things I'd like feedback on:
- Is  there a particular style convention I should adhere to? I see there's a policy on indentation …
> Descriptors

- bluepy/btle.py
This diff gracefully handles `self._serviceMap` being `None` initially. Otherwise would crash on line 438
> Fixing crash when getServiceByUUID is called before services are cached

- MANIFEST.in
- setup.py
Include compiled "bluepy-helper".
I prefer install this library using `pip install bluepy`. But this wasn't work.
This PR will be fix that problem.
> Fix python packaging

- bluepy/btle.py
small update to allow connect to be called with a ScanEntry object just like the constructor is able to.
> updating Peripheral.connect to allow ScanEntry

- setup.py
This is a workaround, as the makefile should properly handle these.
However, the amount of compiled code is small so this fix should
suffice.
> Fixed setup.py to handle environments where MAKEFLAGS=-jx is set.

- bluepy/bluepy-helper.c
- bluepy/btle.py
- bluepy/scanner.py
- Add commands `pasv` and `pasvend` to bluepy-helper using HCI to listen for `ADV_IND` packages only
- Add option `passive` to Scanner class, switching between `scan`/`scanend` and `pasv`/`pasvend`
- Add example script `scanner.py`
> Add passive scan capabilities

- bluepy/btle.py
Here is the resp value that is causing me trouble : 
{'state': ['scan'], 'rsp': ['stat'], 'mtu': [0], 'dst': ['(null)'], 'sec': ['low']}
Should solve #182
> Do not raise Exception when type is "stat" and state is not "disc"

- bluepy/btle.py
Make the subprocess for bluepy-helper ignore SIGINT so controlling Python applications can shut down cleanly.
Now applications can do something like:
```
try:
delegate.writeCharacteristic(cccd, struct.pack('<bb', 0x01, 0x00))
while True:
if delegate.waitForNotifications(1.0):
continue
except KeyboardInterrupt:
delegate.writeCharacteristic(cccd, struct.pack('<bb', 0x00, 0x00))
del delegate
```
This addresses https://github.com/IanHarvey/bluepy/issues/191
> bluepy-helper should ignore SIGINT 

- bluepy/btle.py
I hope you find this useful: being able to refer to the SDID codes by name rather than by absolute value makes client code more readable.
> Add symbolic constants for the SDID codes.

- bluepy/btle.py
I also experienced crashing bluepy thanks to broken device names (as in #259).
This change fixes it.
The fallback to ISO-8859-1 worked in my case. For other nasty situations I also added a default handler for good measure.
> Handling for broken device names. Closes #259

- bluepy/Makefile
Changed the makefile so it doesn't override parameters coming from the environment, to let toolchains that can hook into pip (such as OpenWRT/LEDE) provide their own compilation setup.
The resulting bluepy-helper has the same MD5 sum on my machine with and without those changes, but attempting to compile this using openWRT's toolchain creates a binary of the correct architecture for the compilation target instead of the compilation host.
> Makefile : Don't override env. variables

- bluepy/bluepy-helper.c
- bluepy/btle.py
Fixes for issue #282
Return error code instead of abruptly exiting on passive scan disable failure.
Remove extra mgmt success message on passive scan interruption/disconnect to match active scan behavior.
> Fixes for passive scan interruption

- bluepy/btle.py
The bluepy-helper passes the underlying bluetooth status code to the btle.py module, but the `_waitResp` function does not do anything with the value.  This change passes the `estat` value through to the `BTLEException` so that it is possible to interrogate the true bluetooth status code.
> Expose the estat code returned by bluepy-helper through the BTLEException

- bluepy/btle.py
Specific Exceptions allow to distinguish between a permission problem (not sudo) and and interface that does not support BLE.
I added `BTLEPermissionError` to indicate permission issues and `BTLEInterfaceSupportError` for interfaces that do not support BLE.
This fixes #316
> Add BTLEPermissionError and BTLEInterfaceSupportError

- bluepy/btle.py
Hi,
As discussed in commented in #302 , switch from ord to struct.unpack_from.
However only tested in python 2 as of today, reading local OOB on a Raspberry Pi 3, giving OOB data to a BLE device, and then performing secure pairing.
> Re #302 (OOB support) : switch from ord() to struct.unpack_from() for python 3 support.

- bluepy/bluepy-helper.c
- bluepy/btle.py
There are peripherals that initiate an MTU exchange request, but currently bluepy rejects the request and sends a not supported response.
These changes update the bluepy-helper to register for and handle the ATT_OP_MTU_REQ event.  Additional changes were made to btle.py track the MTU and add the ability the to get the current value.
> Handle MTU request from peripheral

- bluepy/thingy52.py
Right now, none of the `disable()` methods in `thingy52` work because they contain calls to class methods which are not called using `self.`.
In addition, I also removed an unused import and a call to a non-existing method.
> Bugfix: use self in disable() methods in thingy52

- bluepy/btle.py
See https://github.com/IanHarvey/bluepy/issues/354
bluepy may read multiple lines from the helper, but readline only
returns the first one.  Subsequent calls to poll() will delay (and
possibly return None) because there is no way to know that additional
lines are ready to return.
This uses a very simple loop to queue an entry every time readline
returns a line.  The queue lets you easily check for ready lines, as
well as supporting get() with a timeout.
> Fix bug in readline handling if multiple lines available

- bluepy/btle.py
The extra indentation in _getResp causes the check for not receiving the desired response type to be skipped.
I'm assuming that check allows the function to loop until the desired response is received.
But due to the extra indentation it's skipped.
> Remove extra indentation in _getResp() function causing it to not wait for the "wanted" response type

- tests/test_uuid.py
This tests all methods in the UUID class, except for `__hash__()` and `getCommonName()`. This is part of an overall attempt to get unittests working as requested in Bluepy's README. Feedback is appreciated.
> Unittest for UUID class

- bluepy/btle.py
- docs/peripheral.rst
Added option to pass timeout parameter to the peripheral constructor to be used as timeout for "trying to connect" period.
Possible resolution for issue #303
> Added option for timeout while connecting to peripheral

- bluepy/btle.py
As currently implemented writeCharacteristic(..., withResponse=True) gets stuck if peripheral does not respond.
> Add optional timeout to writeCharacteristic()
