IanHarvey/bluepy

- bluepy/bluepy-helper.c
This method waits on a status reponse from the helper to
indicate success
> Send a status to bluepy.setSecurityLevel()

- bluepy/btle.py
I'm not sure how this is working for anyone with that tab in there.
> Change tabs to spaces

- bluepy/btle.py
Added management for indications based on the existing code for notifications
> Updated btle.py to include indications

- .gitignore
- bluepy/btle.py
Remove trailing spaces
Add vim swp to .gitignore
> Fix mixing tabs and spaces

- bluepy/btle.py
Hi,
Looks like there is a tab indenting problem in btle.py. This pull request fixes that.
> fixed tab/space indenting

- bluepy/Makefile
- bluepy/bluepy-helper.c
- bluepy/btle.py
I have also added a few goodies:
- replaced some spaces by tabs
- added the possibility to wait for several responses types
> Add mgmt interface to bluepy-helper to write automatic scripts for pairing/bonding regressions

- bluepy/btle.py
This adds a shebang and the executable bit to btle.py so it can be used from the command line.
> Make btle.py executable from the command line

- README.md
I think this used to be a Makefile, but now uses Python's setup library.
> Fix build steps.

- bluepy/__init__.py
- bluepy/get_services.py
I'm trying to make use of this with Python v3 and without those changes it won't work. I guess there will be others too
> Make this Python v3 compatible

- docs/scanner.rst
The example LE scanner code wasn't actually runnable.  I've tuned it up and it now works correctly.
> Fixed scanner example code

- bluepy/sensortag.py
Added the capability for the script to read the battery level (in percent)  in SensorTag with BLE v1.3 fw.
> Battery reading for SensorTag

- bluepy/blescan.py
- bluepy/get_services.py
Please consider merging those formatting changes. They are mostly created with autopep8. I don't have any advanced tests to check if the code hasn't been broken, but the basic functionality seems to be OK.
> Formatting changes as per PEP8

- README.md
- bluepy/__init__.py
- bluepy/thingy52.py
- setup.py
Added support for Nordic Semiconductor ASA IoT Sensor Kit, Thingy:52. Example shows how interface can be used to send/read/get notified by data from the Thingy:52.
See https://www.nordicsemi.com/eng/Products/Nordic-Thingy-52 for more information. If its desirable to test before merge (i have tested both Python2 and 3 on the Raspberry Pi) let me know and i could get one module shipped to you so that you can test it and verify that its working/suggest any changes.
> Added Thingy:52 support.

- docs/peripheral.rst
Fixed parameter names in the documentation
> Fixed peripheral documentation

- docs/scanner.rst
I added comments to the *Sample Code* so that it's easier for newbies (like me!) to understand everything that's happening. Thanks for such a useful library -- I hope this helps.
> Comments for the sample code

- bluepy/bluepy-helper.c
- bluepy/btle.py
Hi,
I faced the issue that if helper is started without argument, the mgmt is not setup. I think in this case the mgmt should be setup for the default index (0).
> Add support for getting local OOB and setting OOB for a remote device

- bluepy/btle.py
- docs/peripheral.rst
Helper function allowing to get current device state
Signed-off-by: Przemo Firszt <przemo@firszt.eu>
> Add getState method to peripheral

- bluepy/thingy52.py
- bluepy/version.h
Hi Ian (and other contributors)
Thanks for your work on this great library.
I noticed that the values from the gas sensor were being incorrectly decoded (assumed top be base 10, sometimes causing an exception), so here's the fix.
Best regards,
Agnetha
> Fixing decoding of Thingy52 gas sensor

- docs/assignednumbers.rst
Fixed Bluetooth specification URL
> Update assignednumbers.rst - URL fix

- bluepy/btle.py
This could fix #433. However I do not have a complete understanding of this library, and I am willing to work further on this.
> Prevents TypeError in Peripheral._connect().
